Output plugin s3
ozonru/file.d pull request #12
Opened 2021-07-15 13:42 UTC by nevanna

2021-07-20 10:25 UTC, vitkovskii commented on plugin/output/file/file.go
> +	AdditionalFunc func(string) ()
SealupCallback

2021-07-20 10:25 UTC, vitkovskii commented on plugin/output/s3/compress.go
> +		z.logger.Panicf("could not get file inforamtion for file: %s, error: %s", fileName, err.Error())
`inforamtion` => `information`

2021-07-20 10:25 UTC, vitkovskii commented on plugin/output/s3/s3.go
> +	AccessKey       string `json:"accessKey" required:"true"`
use underscore: `access_key`

2021-07-20 10:25 UTC, vitkovskii commented on plugin/output/s3/s3.go
> +	Secure          bool   `json:"insecure" default:"false"`
Secure or insecure ?))))

2021-07-20 10:25 UTC, vitkovskii commented on plugin/output/s3/s3.go
> +	SecretAccessKey string `json:"secretKey" required:"true"`
SecretKey?

2021-07-20 10:25 UTC, vitkovskii commented on plugin/output/s3/s3.go
> +	p.uploadCh = make(chan string, p.config.WorkersCount_)
it should be different worker count for upload and for compress

2021-07-20 10:25 UTC, vitkovskii commented on plugin/output/s3/s3.go
> +		p.compressor.compress(p.compressor.getName(f), f)
pass compress job to worker

2021-07-20 10:25 UTC, vitkovskii commented on plugin/output/s3/s3.go
> +				//delete archive after uploading
log here successful uploading

2021-08-03 15:39 UTC, vitkovskii requested changes

2021-08-03 15:39 UTC, vitkovskii commented on plugin/output/s3/s3.go
> +	p.compressor = getNewCompressor(p.logger)
`NewCompressor`

2021-08-03 15:39 UTC, vitkovskii commented on plugin/output/s3/s3.go
> +	//Initialize minio client object.
lowercase and space after `//`

2021-08-03 15:39 UTC, vitkovskii commented on plugin/output/s3/s3.go
> +	//set up compression
lowercase and space after `//`

2021-08-03 15:39 UTC, vitkovskii commented on plugin/output/s3/s3.go
> +		p.logger.Panicf("bucket: %s, does not exist", p.config.Bucket)
Error

2021-08-03 15:39 UTC, vitkovskii commented on plugin/output/s3/s3.go
> +	p.uploadExistedFiles()
`uploadExistingFiles`

2021-08-03 15:39 UTC, vitkovskii commented on plugin/output/s3/s3.go
> +		p.uploadCh <- z
send files further to upload in the compressing stage
if you do it here you'll wait till all files will be compressed and only after that you call uploading stage

2021-08-03 15:39 UTC, vitkovskii commented on plugin/output/s3/s3.go
> +		if err := os.Remove(f); err != nil {
it should be in the compression state or you may forget to do it in other place

2021-08-03 15:39 UTC, vitkovskii commented on plugin/output/s3/s3.go
> +//uploadWork uploads compressed files from channel to s3 and then delete compressed file
space

2021-08-03 15:39 UTC, vitkovskii commented on plugin/output/s3/s3.go
> +			err := p.uploadCompressedFile(compressed)
`uploadToS3`

2021-08-03 15:39 UTC, vitkovskii commented on plugin/output/s3/s3.go
> +			p.logger.Errorf("could not upload object: %s, error: %s", compressed, err.Error())
log here how much time we'll be wait for next attmpt

2021-08-06 14:33 UTC, nevanna commented on plugin/output/s3/s3.go
> +		p.logger.Panicf("compression type: %s is not supported", p.config.CompressionType)
Fatalf

2021-09-01 14:58 UTC, merged